#!/bin/sh
#
# urfetch - a wee lil fetch that does what u want and nothing else
# based off of ufetch

## INFO
# user is already defined
host="$(cat /etc/hostname)"
os='windowslmao' #you should know this by now
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
shell="$(basename "${SHELL}")"
# string to show your colors
colstr='░▓█▓'

## DEFINE COLORS
# probably don't change these
if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi
# you change the order or your colors here
color="${black}${colstr}${red}${colstr}${green}${colstr}${yellow}${colstr}${blue}${colstr}${magenta}${colstr}${cyan}${colstr}${white}${colstr}"

# style rules for output - change until your happy
lc="${reset}${bold}${magenta}"      # labels
nc="${reset}${bold}${blue}"         # user and hostname
ic="${reset}${cyan}"                # info
c0="${reset}${cyan}"                # ascii art
ft1="${reset}${bold}${magenta}"     # flavortext style 1
ft2="${reset}${cyan}"               # flavortext style 2

## OUTPUT
### reaarange, change ascii art, change or add flavor text, or add or remove colorbars here
### this ascii art came from open https://manytools.org/hacker-tools/ascii-banner/
cat <<EOF

${c0}                 ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}   \│/┬ ┬┬─┐\│/  ${lc}OS: ${ic}${os}${reset}
${c0}   ─ ─│ │├┬┘─ ─  ${lc}KERNEL: ${ic}${kernel}${reset}
${c0}   /│\└─┘┴└─/│\  ${lc}UPTIME: ${ic}${uptime}${reset}
${c0} ┌─┐┌─┐┌┬┐┌─┐┬ ┬ ${lc}SHELL: ${ic}${shell}${reset}
${c0} ├┤ ├┤  │ │  ├─┤   
${c0} └  └─┘ ┴ └─┘┴ ┴ ${ic}${color}${reset} 
${c0}    (changeme)   ${lc}urFetch is: ${ic}Best Fetch!${reset} 
${c0}                 ${ic}${color}${reset}

EOF
