#!/bin/bash
# urfetch - a wee lil fetch that does what u want and nothing else
# based off of ufetch
## color and style
# takes number 0-15, 0 is black, 7 is white, the rest depends on your terminal's colorscheme
function setColor () { tput setaf "$1";}
#back to default color
function clearColor () { tput sgr0;}
function setBold () { tput bold;}
#takes a string and prints it in every color
function printColor () { for i in {0..15}; do (tput setaf $i); printf '%s' "$1"; done;}
colorBar=$( printColor "█▓" )
colorWave=$( printColor "~*~")
# styles
function lc () { clearColor; setBold; setColor 4;}     # rest of text
function nc () { clearColor; setBold; setColor 5;}    # user and hostname
function c0 () { clearColor; setBold; setColor 6;}      # ascii art
# flavor text
## list of options
flavor=($(lc)"urFetch is good Fetch!"
	$(lc)"urFetch is great Fetch!"
	$(lc)"urFetch is best Fetch!")
##copy and paste the following line where ever youd like a random flavortext
##${flavor[$(($RANDOM % ${#flavor[@]}))]}
## OUTPUT
### reaarange, change ascii art, place flavor text, or add or remove colorbars here
### replace windwosLmaos with your distro, you should know it by now
### if you know your shell, an hostname and know they won't change you can hard code them to make this a bit quicker
### this ascii art came from open https://manytools.org/hacker-tools/ascii-banner/
cat <<EOF
$(c0)                 $(nc)${USER}$(lc)@$(nc)$(cat /etc/hostname)
$(c0)   \│/┬ ┬┬─┐\│/  $(lc)windwosLmaos 
$(c0)   ─ ─│ │├┬┘─ ─  $(lc)$(uname -sr) 
$(c0)   /│\└─┘┴└─/│\  $(lc)$(uptime -p)
$(c0) ┌─┐┌─┐┌┬┐┌─┐┬ ┬ $(lc)$(basename "$SHELL")
$(c0) ├┤ ├┤  │ │  ├─┤   
$(c0) └  └─┘ ┴ └─┘┴ ┴ $colorBar
$(c0)    (changeme)   ${flavor[$((RANDOM % ${#flavor[@]}))]}
$(c0)                 $colorWave
EOF
